### ISSUE TITLE
"Форма редактирования задачи" - несохранение введенных ранее значений чек-бокс поля "Исполнитель" при вызове формы

### ISSUE THREAD

**Issue by AndreyDyakonov** [AndreyDyakonov/QA_traineeship#36]
1. Нажать на элемент "Задачи"
2. Обратить внимание на значения в колонке "Исполнитель(и)"  
3. Нажать на кнопку "Изменить"
4. Обратить внимание на значения чек-бокс поля ""Исполнитель(и)" 

Актуальный результат:
Значения (флаги) чек-бокс поля "Исполнитель(и)" сброшены

Ожидаемый результат:
Значения (флаги) чек-бокс поля "Исполнитель(и)" установлены согласно введенным ранее значениями

Окружение: Google Chrome Версия 108.0.5359.99 (Официальная сборка), (64 бит)

Приложение:

https://user-images.githubusercontent.com/85252690/208651742-cc937337-cea8-421f-be7e-7709781d5c77.mp4

**Comment by marinamatveyuk** [comment]
Смотри комментарий к дефекту #33

**Comment by AndreyDyakonov** [comment]
Дефект объединен с https://github.com/AndreyDyakonov/QA_traineeship/issues/33
Не актуален как отдельная задача
